"""Initial Neon DB Setup

Revision ID: 635d76bb3845
Revises: 
Create Date: 2025-11-04 02:37:19.055292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635d76bb3845'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('next_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'academic_year', name='_class_year_uc')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('zk_user_id', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zk_user_id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_zk_id', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['student_zk_id'], ['students.zk_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_zk_id', 'date', name='_student_date_uc')
    )
    op.create_table('final_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_zk_id', sa.String(length=20), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('overall_total', sa.Integer(), nullable=True),
    sa.Column('overall_ranking', sa.Integer(), nullable=True),
    sa.Column('general_result', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_zk_id'], ['students.zk_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_zk_id', 'academic_year', name='_final_grade_uc')
    )
    op.create_table('final_student_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_zk_id', sa.String(length=20), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('overall_total_grade', sa.Float(), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('general_result', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['student_zk_id'], ['students.zk_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_zk_id', 'academic_year', name='_final_student_result_uc')
    )
    op.create_table('final_subject_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_zk_id', sa.String(length=20), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('first_acc_grade', sa.Float(), nullable=True),
    sa.Column('first_acc_result', sa.Float(), nullable=True),
    sa.Column('second_acc_grade', sa.Float(), nullable=True),
    sa.Column('second_acc_result', sa.Float(), nullable=True),
    sa.Column('subject_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student_zk_id'], ['students.zk_user_id'], ),
    sa.ForeignKeyConstraint(['subject_name'], ['subjects.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_zk_id', 'academic_year', 'subject_name', name='_final_subject_grade_uc')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_zk_id', sa.String(length=20), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(length=20), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('homework_grade', sa.Integer(), nullable=True),
    sa.Column('oral_grade', sa.Integer(), nullable=True),
    sa.Column('attendance_grade', sa.Integer(), nullable=True),
    sa.Column('written_grade', sa.Integer(), nullable=True),
    sa.Column('total_grade', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_zk_id'], ['students.zk_user_id'], ),
    sa.ForeignKeyConstraint(['subject_name'], ['subjects.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_zk_id', 'academic_year', 'month_name', 'subject_name', name='_monthly_grade_uc')
    )
    op.create_table('mid_term_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_zk_id', sa.String(length=20), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('accumulated_grade', sa.Integer(), nullable=True),
    sa.Column('end_term_grade', sa.Integer(), nullable=True),
    sa.Column('term_total_grade', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_zk_id'], ['students.zk_user_id'], ),
    sa.ForeignKeyConstraint(['subject_name'], ['subjects.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_zk_id', 'academic_year', 'subject_name', name='_mid_term_grade_uc')
    )
    op.create_table('monthly_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_zk_id', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(length=50), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('homework_grade', sa.Integer(), nullable=True),
    sa.Column('oral_grade', sa.Integer(), nullable=True),
    sa.Column('attendance_grade', sa.Integer(), nullable=True),
    sa.Column('written_grade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_zk_id'], ['students.zk_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_zk_id', 'year', 'month_name', 'subject_name', name='_unique_monthly_grade_per_subject')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_grades')
    op.drop_table('mid_term_grades')
    op.drop_table('grades')
    op.drop_table('final_subject_grades')
    op.drop_table('final_student_results')
    op.drop_table('final_grades')
    op.drop_table('attendance')
    op.drop_table('students')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('classes')
    # ### end Alembic commands ###
